const data = {
    products: [
        {
            _id: '1',
            name: "Beer ",
            category: 'category 1',
            image: '/images/product1.jpg',
            price: 120,
            brand: 'Brand 1',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '2',
            name: "Beer 2",
            category: 'category 2',
            image: '/images/product1.jpg',
            price: 100,
            brand: 'Brand 1',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '3',
            name: "Beer 3",
            category: 'category 1',
            image: '/images/product1.jpg',
            price: 110,
            brand: 'Brand 2',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '4',
            name: "Beer 4",
            category: 'category 2',
            image: '/images/product1.jpg',
            price: 100,
            brand: 'Brand 2',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '5',
            name: "Beer 5",
            category: 'category 3',
            image: '/images/product1.jpg',
            price: 80,
            brand: 'Brand 3',
            rating: 3.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '6',
            name: "Beer 6",
            category: 'category 2',
            image: '/images/product1.jpg',
            price: 70,
            brand: 'Brand 3',
            rating: 4,
            numReviews: 10,
            description: 'hight quality product',
        },
    ]
}
export default data;